### ISSUE TITLE
Removing nobackpressure support

### ISSUE THREAD

**Issue by gustavnikolaj** [gustavnikolaj/hijackresponse#10]
Turns out that I just found the same bug as you with the compression middleware @papandreou . @abugnais ran into a problem with a hanging response with express-autoprefixer.

The backpressure support is something that I added because it seemed nice, but it's a bit crude and we haven't had a real need for it yet or even properly demonstrated that it fixes any problems.

I think it would make sense to release a new major version where it is removed - effectively making disableBackPressure the default, and removing the flag.

Then we can reintroduce it as an option at a later point in time if we find that we need it. What are your thoughts?

**Comment by papandreou** [comment]
Oh, man. I guess the alternative is to fix the misbehaving compression middleware?

**Comment by abugnais** [comment]
I agree, although it'll be much nicer of we can get the compression middleware fixed instead!

**Comment by gustavnikolaj** [comment]
Yep, but honestly, I feel less and less confident about that feature. I'd rather just remove it and do the simple thing that we know works.

**Comment by gustavnikolaj** [comment]
Fixed by above referenced commit and released in v2.0.0. express-autoprefixer released with a fix in v5.1.1
