### ISSUE TITLE
Types

### ISSUE THREAD

**Issue by Maetes** [gustavnikolaj/hijackresponse#17]
Hi,

are types availiable? Can't find them through?

**Comment by gustavnikolaj** [comment]
Hi @Maetes,

No, there's no TypeScript type definitions for this project.

**Comment by gustavnikolaj** [comment]
@MatthiasKunnen told me in #19:

> FYI I have created types for hijackresponse here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/47540

🚀 

Note, these are likely only supporting the v4-release

**Comment by MatthiasKunnen** [comment]
Only v4 release indeed. If you want to maintain the types we could include it in the library itself.
