### ISSUE TITLE
Using an actual Proxy for proxyRes

### ISSUE THREAD

**Issue by gustavnikolaj** [gustavnikolaj/hijackresponse#25]
When doing #24 I tried a few times to wrangle a proxy in there. It fails for the tests in `hijackResponse.spec.js` which uses nested hijacks;

```js
hijackResponse(res, (hijackedResponseBody, res) => {
  // hijack outer
  hijackResponse(res, (hijackedResponseBody, res) => {
    // hijack inner
    hijackedResponseBody.pipe(transform2).pipe(res)
  });

  hijackedResponseBody.pipe(transform1).pipe(res)
}); 
```

That is not a construct I have seen in the wild, but something that I used in tests to simulate the following case in request:

```js
const app = express();

app
  .use((req, res, next) => {
    hijackResponse(res, (hijackedResponseBody, res) => {
      hijackedResponseBody.pipe(transform2).pipe(res);
    }); 
    next();
  })
  .use((req, res, next) => {
    hijackResponse(res, (hijackedResponseBody, res) => {
      hijackedResponseBody.pipe(transform1).pipe(res);
    }); 
    next();
  });
```

The express case is actually not nested hijacks as such - it's more sequential. If you were to write it out without express, it would be more akin to:

```js
hijackResponse(res, (hijackedResponseBody, res) => {
  // hijack inner
  hijackedResponseBody.pipe(transform2).pipe(res);
}); 

hijackResponse(res, (hijackedResponseBody, res) => {
  // hijack outer
  hijackedResponseBody.pipe(transform1).pipe(res);
}); 
```

Dropping support for the nested case is a breaking change, but I am not sure that I have ever seen the module actually looked like that.

**Comment by gustavnikolaj** [comment]
A penny for your thoughts, @papandreou :-)

**Comment by papandreou** [comment]
I'm afraid I don't really grasp how the use of a `Proxy` would be executed, or why it causes problems in that snippet? 🤔

**Comment by gustavnikolaj** [comment]
I've submitted a PR (#29) with my suggested implementation. 

It causes a problem here, as the hijacking is done on top of the proxied-res instead of the actual res object. I could maybe fix that by using a corresponding setter to my getter in the PR implementation - but when I tried that I ran into problems orchestrating it that lead to me having to figure out some sort of internal book keeping on who had hijacked the res in which order, to make sure that the right versions of the monkey-patched methods were called.

All of that lead to the conclusion in this issue - I'm reasonably sure that my tests using the nested pattern are bogus, and won't ever happen in real use, unless you are using node core's http-server directly at least.

**Comment by gustavnikolaj** [comment]
@papandreou I decided to include htis in #30 in commit https://github.com/gustavnikolaj/hijackresponse/commit/8de1fa521849e6a40bacc7811177dd1237843158

When we don't try to have the writable-side pass as a res, it makes less sense to support this usecase. I added an explicit rejection to make it clear that it is unsupported and so we don't just error out in a weird way.
