### ISSUE TITLE
Write migration guide to v5

### ISSUE THREAD

**Issue by gustavnikolaj** [gustavnikolaj/hijackresponse#33]

**Comment by gustavnikolaj** [comment]
If anyone finds this message and needs help migrating forward, please reach out or drop a comment here. I figure that the crowd using this module is small enough that it really doesn't matter all that much. :-)

**Comment by richardsimko** [comment]
Is there a changelog with breaking changes between 4.0 and 5.0?

**Comment by gustavnikolaj** [comment]
@richardsimko the breaking changes are these two PRs:

- https://github.com/gustavnikolaj/hijackresponse/pull/24
- https://github.com/gustavnikolaj/hijackresponse/pull/30

If you have any issues I'm happy to help. :-)

**Comment by gustavnikolaj** [comment]
To sum up, with v4, you would have:

```js
app.use(function(req, res, next) {
  hijackResponse(res, function(err, res) {
    if (err) {
      res.unhijack(); // Make the original res object work again
      return next(err);
    }

    res.setHeader("X-Hijacked", "yes!");
    res.removeHeader("Content-Length");

    res.pipe(transformStream).pipe(res);
  });
  next();
});
```

You would now do:

```js
app.use((req, res, next) => {
  hijackResponse(res, next).then(({ readable, writable }) => {
    if (iWantToUnhijack) {
      return readable.pipe(writable);
    }

    readable.pipe(transformStream).pipe(writable);
  });
});
```

The API changed from callback to promise based (#30). You pass next in along with the res object, and the promise will resolve with two streams: `readable` and `writable`.

`readable` is the hijacked response from other middlewares and handlers. `writable` is the unmodified res object from before hijacking. I split the old monkey-patched duplex res stream from the callback out into two separate streams, to make it easier to reason about (#24). 

The changes also addressed any oddities that the v4 code had (e.g. breaking back-preassure, because the `res` stream handed back couldn't handle that properly).

**Comment by richardsimko** [comment]
Thanks for the comprehensive guide! I managed to migrate using this.

**Comment by gustavnikolaj** [comment]
@richardsimko Great! Happy to hear that it worked out.

If you are able to share what you are building with this module I would love to hear about it :-)

**Comment by richardsimko** [comment]
Sure, I've just build a modified and customized version of https://github.com/cloudflare/netjet in order to send preload links for https://awardfares.com :)

**Comment by gustavnikolaj** [comment]
Cool :-) It's always interesting seeing what people use this for :-)
